// Mocks generated by Mockito 5.1.0 from annotations
// in pokedex_flutter/test/mocks/generator.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pokedex_flutter/features/pokedex/models/pokemon_details.dart'
    as _i3;
import 'package:pokedex_flutter/features/pokedex/models/pokemon_type.dart'
    as _i6;
import 'package:pokedex_flutter/features/pokedex/models/pokemon_type_details.dart'
    as _i2;
import 'package:pokedex_flutter/features/pokedex/repositories/pokemon_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakePokemonTypeDetails_0 extends _i1.Fake
    implements _i2.PokemonTypeDetails {}

class _FakePokemonDetails_1 extends _i1.Fake implements _i3.PokemonDetails {}

/// A class which mocks [PokemonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRepository extends _i1.Mock implements _i4.PokemonRepository {
  MockPokemonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.PokemonTypeDetails> getPokemonTypeDetails(int? id) =>
      (super.noSuchMethod(Invocation.method(#getPokemonTypeDetails, [id]),
              returnValue: Future<_i2.PokemonTypeDetails>.value(
                  _FakePokemonTypeDetails_0()))
          as _i5.Future<_i2.PokemonTypeDetails>);
  @override
  _i5.Future<_i3.PokemonDetails> getPokemonDetails(int? id) =>
      (super.noSuchMethod(Invocation.method(#getPokemonDetails, [id]),
              returnValue:
                  Future<_i3.PokemonDetails>.value(_FakePokemonDetails_1()))
          as _i5.Future<_i3.PokemonDetails>);
  @override
  _i5.Future<List<_i6.PokemonType>> getPokemonTypes() => (super.noSuchMethod(
          Invocation.method(#getPokemonTypes, []),
          returnValue: Future<List<_i6.PokemonType>>.value(<_i6.PokemonType>[]))
      as _i5.Future<List<_i6.PokemonType>>);
}
